Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.6.1
  Exclude:
  - 'bin/*'
  - 'config/**/*'
  - 'db/**/*'
  - 'vendor/bundle/**/*'
  - 'spec/rails_helper.rb'
  - 'spec/spec_helper.rb'

# 日本語でのコメントを許可
AsciiComments:
  Enabled: false
