version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/app
    ports:
      - "3000:3000"
    links:
        - db
    tty: true


  db:
    image: postgres:10
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    ports:
      - "3306:3306"
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=Va+34yMw

  test_db:
    image: postgres:10
    ports:
      - "3307:3307"
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=Va+34yMw